set -g base-index 1
setw -g pane-base-index 1
set -g set-clipboard on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'sainnhe/tmux-fzf'


## resurrection configs
set -g @plugin 'tmux-plugins/tmux-resurrect'
# for vim
set -g @resurrect-strategy-vim 'session'
# for neovim
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

# shortcuts for the session manager
bind P run-shell "$HOME/.local/bin/tmux-sm pin '#{session_name}'"
bind X run-shell "$HOME/.local/bin/tmux-sm unpin '#{session_name}'"
bind Z run-shell "$HOME/.local/bin/tmux-sm unmark '#{session_name}'"
bind M run-shell "$HOME/.local/bin/tmux-sm manual-idle '#{session_name}'"

# shortcuts for using the current pane's cwd when splitting to a pane
bind '"' splitw -c '#{pane_current_path}'
bind '%' splitw -h -c '#{pane_current_path}'


# client switching
bind-key Tab switch-client -l

# list all sessions including idle: leader+A
bind A run-shell "tmux-sm list --all | tmux display-message -p ''"

# sort based on these tags (or name)
bind s choose-tree -sZ -O name -r

# plugin configurations
set -g @rose_pine_variant 'main' # Options are 'main', 'moon' or 'dawn'
set -g @rose_pine_host 'on' # Enables hostname in the status bar
set -g @rose_pine_directory 'on' # Turn on the current folder component in the status bar
set -g @rose_pine_user 'on' # Turn on the username component in the statusbar


# the terminal coloring
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# keybindings
unbind C-b
set -g prefix C-Space

# so we can create sessions nicely and neatly
bind N command-prompt "new-session -s '%%'"


# get to vi keymode
set-window-option -g mode-keys vi

# Optional but nice: make copy mode feel like vim
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes with prefix + Ctrl + hjkl (vim-style)
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
